
import { DataTypes, Model } from 'sequelize';
import { sequelize } from '../../../db/sequelize.js';
import { LeadUser } from '../purchase/leadUser.model.js';

export class Lead extends Model {}

Lead.init(
  {
    id: {
      type: DataTypes.INTEGER.UNSIGNED,
      autoIncrement: true,
      primaryKey: true,
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    email: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    phone: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    address: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    zipCode: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    state: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    type: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    status: {
      type: DataTypes.ENUM('public', 'private'),
      allowNull: false,
      defaultValue: 'public',
    },
    saleCount: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0,
    },
    emails: {
      type: DataTypes.JSON,
      allowNull: true,
      comment: 'Personalized emails generated by OpenAI',
    },
  },
  {
    sequelize,
    modelName: 'Lead',
    tableName: 'Lead',
    timestamps: true,
  },
);

// Associations (call after all models are defined)
export const associate = (models) => {
  LeadUser.belongsTo(models.User, { foreignKey: 'userId' });
  LeadUser.belongsTo(models.Lead, { foreignKey: 'leadId' });
  models.User.hasMany(LeadUser, { foreignKey: 'userId' });
  models.Lead.hasMany(LeadUser, { foreignKey: 'leadId' });
};
